# Generated by Django 5.1.7 on 2025-12-31 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_score', models.PositiveIntegerField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.program')),
            ],
            options={
                'unique_together': {('program', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exams.program')),
            ],
            options={
                'ordering': ['index_number'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('max_score', models.PositiveIntegerField()),
                ('step_order', models.PositiveIntegerField()),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='exams.procedure')),
            ],
            options={
                'ordering': ['step_order'],
                'unique_together': {('procedure', 'step_order')},
            },
        ),
        migrations.CreateModel(
            name='StudentProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scored', 'Scored'), ('reconciled', 'Reconciled')], default='pending', max_length=20)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('examiner_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examiner_a_assignments', to=settings.AUTH_USER_MODEL)),
                ('examiner_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examiner_b_assignments', to=settings.AUTH_USER_MODEL)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.procedure')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.student')),
            ],
            options={
                'unique_together': {('student', 'procedure')},
            },
        ),
    ]
