# Generated by Django 6.0.3 on 2026-04-02 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_score', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('abbreviation', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('step_order', models.PositiveIntegerField()),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='exams.procedure')),
            ],
            options={
                'ordering': ['step_order'],
                'unique_together': {('procedure', 'step_order')},
            },
        ),
        migrations.AddField(
            model_name='procedure',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.program'),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_plan_lock_on_submit', models.BooleanField(default=True, help_text='When ON (default): a care plan is locked immediately after an examiner submits it and cannot be changed. When OFF: any examiner can overwrite a previously submitted care plan score.', verbose_name='Lock care plan after submission')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='exams.level')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exams.program')),
            ],
            options={
                'ordering': ['level', 'index_number'],
            },
        ),
        migrations.CreateModel(
            name='CarePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('max_score', models.PositiveIntegerField(default=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='care_plan_assessments', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_plans', to='exams.student')),
            ],
            options={
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scored', 'Scored'), ('reconciled', 'Reconciled')], db_index=True, default='pending', max_length=20)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_reconciler', models.ForeignKey(blank=True, help_text='The examiner assigned to perform reconciliation (locked once set)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('examiner_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examiner_a_assignments', to=settings.AUTH_USER_MODEL)),
                ('examiner_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examiner_b_assignments', to=settings.AUTH_USER_MODEL)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.procedure')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciled_procedures', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.student')),
            ],
        ),
        migrations.CreateModel(
            name='ReconciledScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('reconciled_at', models.DateTimeField(auto_now=True)),
                ('reconciled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores_reconciled', to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.procedurestep')),
                ('student_procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciled_scores', to='exams.studentprocedure')),
            ],
            options={
                'ordering': ['step__step_order'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureStepScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('is_reconciled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.procedurestep')),
                ('student_procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_scores', to='exams.studentprocedure')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='procedure',
            unique_together={('program', 'name')},
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['program', 'level', 'is_active'], name='exams_stude_program_9e9a10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='careplan',
            unique_together={('student', 'program')},
        ),
        migrations.AddIndex(
            model_name='studentprocedure',
            index=models.Index(fields=['student', 'status'], name='exams_stude_student_4ecbf4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentprocedure',
            unique_together={('student', 'procedure')},
        ),
        migrations.AddIndex(
            model_name='reconciledscore',
            index=models.Index(fields=['student_procedure'], name='exams_recon_student_8e360c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reconciledscore',
            unique_together={('student_procedure', 'step')},
        ),
        migrations.AddIndex(
            model_name='procedurestepscore',
            index=models.Index(fields=['step', 'student_procedure', 'examiner'], name='exams_proce_step_id_2aa4bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='procedurestepscore',
            unique_together={('student_procedure', 'step', 'examiner', 'is_reconciled')},
        ),
    ]
