# Generated by Django 4.2.16 on 2026-01-18 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_score', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('step_order', models.PositiveIntegerField()),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='exams.procedure')),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(blank=True, max_length=20, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.school')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('100', 'Level 100'), ('200', 'Level 200'), ('300', 'Level 300'), ('400', 'Level 400')], default='100', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exams.program')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.school')),
            ],
            options={
                'ordering': ['level', 'index_number'],
            },
        ),
        migrations.CreateModel(
            name='StudentProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scored', 'Scored'), ('reconciled', 'Reconciled')], default='pending', max_length=20)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('examiner_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examiner_a_assignments', to=settings.AUTH_USER_MODEL)),
                ('examiner_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examiner_b_assignments', to=settings.AUTH_USER_MODEL)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.procedure')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciled_procedures', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.student')),
            ],
        ),
        migrations.CreateModel(
            name='ReconciledScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('reconciled_at', models.DateTimeField(auto_now=True)),
                ('reconciled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores_reconciled', to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.procedurestep')),
                ('student_procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciled_scores', to='exams.studentprocedure')),
            ],
            options={
                'ordering': ['step__step_order'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureStepScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('is_reconciled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.procedurestep')),
                ('student_procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_scores', to='exams.studentprocedure')),
            ],
        ),
        migrations.AddField(
            model_name='procedure',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.program'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.school'),
        ),
        migrations.CreateModel(
            name='CarePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('max_score', models.PositiveIntegerField(default=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='care_plan_assessments', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.program')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_plans', to='exams.student')),
            ],
            options={
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='studentprocedure',
            index=models.Index(fields=['school', 'status'], name='exams_stude_school__0cb649_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprocedure',
            index=models.Index(fields=['school', 'student'], name='exams_stude_school__157ba3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentprocedure',
            unique_together={('school', 'student', 'procedure')},
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'index_number'], name='exams_stude_school__14b5fc_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'program'], name='exams_stude_school__40b6b5_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'level'], name='exams_stude_school__5c4262_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('school', 'index_number')},
        ),
        migrations.AlterUniqueTogether(
            name='reconciledscore',
            unique_together={('student_procedure', 'step')},
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['school', 'name'], name='exams_progr_school__042fde_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='procedurestepscore',
            unique_together={('student_procedure', 'step', 'examiner', 'is_reconciled')},
        ),
        migrations.AlterUniqueTogether(
            name='procedurestep',
            unique_together={('procedure', 'step_order')},
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['school', 'program'], name='exams_proce_school__7c8bf1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='procedure',
            unique_together={('school', 'program', 'name')},
        ),
        migrations.AddIndex(
            model_name='careplan',
            index=models.Index(fields=['school', 'student'], name='exams_carep_school__475453_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='careplan',
            unique_together={('school', 'student', 'program')},
        ),
    ]
