# Generated by Django 5.1.7 on 2026-01-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
