# Generated by Django 6.0.3 on 2026-04-08 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_careplan_score_alter_procedure_program_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['id']},
        ),
    ]
