# Generated by Django 5.1.7 on 2026-01-02 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_program_abbreviation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedurestep',
            name='max_score',
        ),
    ]
