# Generated by Django 6.0.3 on 2026-04-18 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_program_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedure',
            options={'ordering': ['id']},
        ),
    ]
