# Generated by Django 5.1.7 on 2026-01-03 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_remove_procedurestep_max_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureStepScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.procedurestep')),
                ('student_procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_scores', to='exams.studentprocedure')),
            ],
            options={
                'unique_together': {('student_procedure', 'step', 'examiner')},
            },
        ),
    ]
