# Generated by Django 6.0.3 on 2026-10-09 18:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_category_procedure_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careplan',
            options={'ordering': ['slot', '-assessed_at']},
        ),
        migrations.AlterUniqueTogether(
            name='careplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='careplan',
            name='slot',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='multiple_care_plans_enabled',
            field=models.BooleanField(default=False, help_text='When ON: examiners may add a second care plan for eligible students (see Care Plan Eligibility). If no eligibility rows exist, all programs and levels are eligible.', verbose_name='Allow a second care plan'),
        ),
        migrations.AlterUniqueTogether(
            name='careplan',
            unique_together={('student', 'program', 'slot')},
        ),
        migrations.CreateModel(
            name='CarePlanEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='care_plan_eligibility', to='exams.level')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_plan_eligibility', to='exams.program')),
            ],
            options={
                'verbose_name_plural': 'Care Plan Eligibility',
                'ordering': ['program_id', 'level_id'],
                'unique_together': {('program', 'level')},
            },
        ),
    ]
