# Generated by Django 4.2.16 on 2026-02-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_studentprocedure_assigned_reconciler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='index_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('100', 'Level 100'), ('200', 'Level 200'), ('300', 'Level 300'), ('400', 'Level 400')], db_index=True, default='100', max_length=3),
        ),
        migrations.AlterField(
            model_name='studentprocedure',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scored', 'Scored'), ('reconciled', 'Reconciled')], db_index=True, default='pending', max_length=20),
        ),
    ]
