# Generated by Django 4.2.16 on 2026-03-13 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_alter_student_full_name_alter_student_index_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='procedurestepscore',
            index=models.Index(fields=['step', 'student_procedure', 'examiner'], name='exams_proce_step_id_2aa4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciledscore',
            index=models.Index(fields=['student_procedure'], name='exams_recon_student_8e360c_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['program', 'level'], name='exams_stude_program_8d65bb_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprocedure',
            index=models.Index(fields=['student', 'status'], name='exams_stude_student_4ecbf4_idx'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='exams.level'),
        ),
    ]
