# Generated by Django 4.2.16 on 2026-03-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['number']},
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='exams_stude_program_8d65bb_idx',
        ),
        migrations.AddField(
            model_name='level',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['program', 'level', 'is_active'], name='exams_stude_program_9e9a10_idx'),
        ),
    ]
