# Generated by Django 5.1.7 on 2025-12-31 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('remark', models.TextField(blank=True)),
                ('score_type', models.CharField(choices=[('examiner', 'Examiner'), ('reconciled', 'Reconciled')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('examiner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('procedure_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.procedurestep')),
                ('student_procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='exams.studentprocedure')),
            ],
            options={
                'unique_together': {('student_procedure', 'procedure_step', 'examiner', 'score_type')},
            },
        ),
    ]
